theme: jekyll-theme-minimal
title: Kirill Loginov's CV
logo: /assets/img/me.png
description: |
  🎯 Senior Software Architect & Tech Leader with 7+ years of excellence in software development.
  
  💡 Specializing in:
  • Enterprise Architecture Design
  • Cloud-Native Solutions
  • Team Leadership & Innovation
  
  🌟 Currently pursuing MBA at Oxford while leading technical initiatives in Dubai's dynamic tech ecosystem.
  
  🚀 Passionate about transforming complex challenges into elegant solutions.