theme: jekyll-theme-minimal
title: Kirill Loginov's CV
logo: /assets/img/id_c.png
description: A confident, self-motivated software engineer with 4 years of experience in software development. A deep researcher and a passionate learner in every aspect of his life, with good analytical and verbal skills.