theme: jekyll-theme-minimal
title: Kirill Loginov's CV
logo: /assets/img/id.jpg
description: A confident, self-motivated software engineer with 6 years of experience in software development. A deep researcher and a passionate learner in every aspect of his life, with good analytical and verbal skills.
show_downloads: false
